[package]
name = "yolo"
version = "0.1.0"
authors = ["flix"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
opencv = "0.74.0"
